name: mobile
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.1.16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  open_file:
  permission_handler:
  path_provider: ^2.0.1
  flutter_downloader: ^1.6.0
  argon_buttons_flutter: ^1.0.6
  intro_slider: ^2.3.4
  package_info:
  smooth_star_rating: ^1.1.1
  flutter_local_notifications: ^4.0.1
  audio_manager: ^0.7.3
  url_launcher: ^6.0.3
  jwt_decoder: ^1.0.3
  flutter_secure_storage: ^3.3.5
  intl: ">=0.14.0"
  provider: ^4.3.2+3
  flutter_cache_manager: ^2.1.0
  curved_navigation_bar: ^0.3.7
  fluttertoast: ^7.1.6
  flutter_localizations:
    sdk: flutter
  http: ^0.12.2
  carousel_slider: ^2.3.1
  flutter_spinkit: ^3.1.0
#  firebase_core:
#  firebase_messaging:
#  firebase_analytics:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/appMainIcon.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/update.png
    - assets/images/whatsapp.png
    - assets/images/telegram.png
    - assets/images/support.png
    - assets/images/16personalities.png
    - assets/images/internetdown.png
    - assets/images/noPicture.png
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/IranSans.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

